version: "3.8"

services:
  web:
    build: .
    ports:
      - "5050:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
